default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: counting_development

test:
  <<: *default
  database: counting_test

production:
  <<: *default
  database: counting_production
  password: <%= ENV['COUNTING_DATABASE_PASSWORD'] %>
  host: 127.0.0.1
